#                   __ _       
#   ___ ___  _ __  / _(_) __ _ 
#  / __/ _ \| '_ \| |_| |/ _` |
# | (_| (_) | | | |  _| | (_| |
#  \___\___/|_| |_|_| |_|\__, |
#                        |___/ 
#---------------------------------------------------------------------
#  _____________ 
# < fill me out >
#  ------------- 
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#---------------------------------------------------------------------


# Download Directory
#   Place path to download attachments to:
DOWNLOAD_DIRECTORY: ""
EXTENSIONS_TO_DOWNLOAD: [".pdf"]


# Email Account Info 
#   Place your email info here:  
EMAIL_INFO:
  EMAIL_ADDRESS: ""
  EMAIL_PASSWORD: ""
  IMAP_HOST: ""
  PORT: 
  ROOT_INBOX: ""

MAIN_PRINTER: ""
MEDIA: ""


