#                   __ _       
#   ___ ___  _ __  / _(_) __ _ 
#  / __/ _ \| '_ \| |_| |/ _` |
# | (_| (_) | | | |  _| | (_| |
#  \___\___/|_| |_|_| |_|\__, |
#                        |___/ 
#---------------------------------------------------------------------
#  _____________ 
# < fill me out >
#  ------------- 
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#---------------------------------------------------------------------


# Download Directory
#   Place path to download attachments to:
DOWNLOAD_DIRECTORY: ""
extensions_to_download: [".pdf", ".doc"]


# Email Account Info 
#   Place your email info here:  
EMAIL_INFO:
  EMAIL_ADDRESS: ""
  EMAIL_PASSWORD: ""
  IMAP_HOST: "imap.gmail.com"
  PORT: 993



